# Generated by Django 3.0.5 on 2020-05-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=30)),
                ('course_description', models.CharField(max_length=300)),
                ('course_credit', models.IntegerField()),
                ('course_instructor', models.CharField(max_length=50)),
                ('course_startDate', models.DateField()),
            ],
        ),
    ]
